version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
