// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_visits.sql

package db

import (
	"context"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT COUNT(*) FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkVisit = `-- name: CreateLinkVisit :one
INSERT INTO link_visits (link_id, ip, user_agent, status, referer) VALUES ($1, $2, $3, $4, $5) RETURNING id, link_id, created_at, ip, user_agent, referer, status
`

type CreateLinkVisitParams struct {
	LinkID    int64
	Ip        string
	UserAgent string
	Status    int32
	Referer   string
}

func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error) {
	row := q.db.QueryRow(ctx, createLinkVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Status,
		arg.Referer,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Status,
	)
	return i, err
}

const getLastLinkVisitByLinkID = `-- name: GetLastLinkVisitByLinkID :one
SELECT id, link_id, created_at, ip, user_agent, referer, status FROM link_visits WHERE link_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLastLinkVisitByLinkID(ctx context.Context, linkID int64) (LinkVisit, error) {
	row := q.db.QueryRow(ctx, getLastLinkVisitByLinkID, linkID)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Status,
	)
	return i, err
}

const listAllLinkVisits = `-- name: ListAllLinkVisits :many
SELECT id, link_id, created_at, ip, user_agent, referer, status FROM link_visits ORDER BY id
`

func (q *Queries) ListAllLinkVisits(ctx context.Context) ([]LinkVisit, error) {
	rows, err := q.db.Query(ctx, listAllLinkVisits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkVisits = `-- name: ListLinkVisits :many
SELECT id, link_id, created_at, ip, user_agent, referer, status FROM link_visits ORDER BY id LIMIT $1 OFFSET $2
`

type ListLinkVisitsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLinkVisits(ctx context.Context, arg ListLinkVisitsParams) ([]LinkVisit, error) {
	rows, err := q.db.Query(ctx, listLinkVisits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
