// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_name, short_url) VALUES ($1, $2, $3) RETURNING id, original_url, short_name, short_url, created_at
`

type CreateLinkParams struct {
	OriginalUrl string
	ShortName   string
	ShortUrl    string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortName, arg.ShortUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLink, id)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, short_name, short_url, created_at FROM links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT id, original_url, short_name, short_url, created_at FROM links
`

func (q *Queries) ListLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.ShortUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shortNameExists = `-- name: ShortNameExists :one
SELECT EXISTS (
  SELECT 1
  FROM links
  WHERE short_name = $1
)
`

func (q *Queries) ShortNameExists(ctx context.Context, shortName string) (bool, error) {
	row := q.db.QueryRow(ctx, shortNameExists, shortName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLink = `-- name: UpdateLink :execrows
UPDATE links SET original_url = $2, short_name = $3, short_url = $4 WHERE id = $1 RETURNING id, original_url, short_name, short_url, created_at
`

type UpdateLinkParams struct {
	ID          int64
	OriginalUrl string
	ShortName   string
	ShortUrl    string
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLink,
		arg.ID,
		arg.OriginalUrl,
		arg.ShortName,
		arg.ShortUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
