// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package db

import (
	"context"
)

const countLinks = `-- name: CountLinks :one
SELECT COUNT(*) FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_name, short_url) VALUES ($1, $2, $3) RETURNING id, original_url, short_name, short_url, created_at
`

type CreateLinkParams struct {
	OriginalUrl string
	ShortName   string
	ShortUrl    string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.OriginalUrl, arg.ShortName, arg.ShortUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, short_name, short_url, created_at FROM links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id int64) (Link, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const linkByShortName = `-- name: LinkByShortName :one
SELECT id, original_url, short_name, short_url, created_at FROM links WHERE short_name = $1
`

func (q *Queries) LinkByShortName(ctx context.Context, shortName string) (Link, error) {
	row := q.db.QueryRow(ctx, linkByShortName, shortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listAllLinks = `-- name: ListAllLinks :many
SELECT id, original_url, short_name, short_url, created_at FROM links ORDER BY id
`

func (q *Queries) ListAllLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.Query(ctx, listAllLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.ShortUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinks = `-- name: ListLinks :many
SELECT id, original_url, short_name, short_url, created_at FROM links ORDER BY id LIMIT $1 OFFSET $2
`

type ListLinksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.ShortUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shortNameExists = `-- name: ShortNameExists :one
SELECT EXISTS (
  SELECT 1
  FROM links
  WHERE short_name = $1
)
`

func (q *Queries) ShortNameExists(ctx context.Context, shortName string) (bool, error) {
	row := q.db.QueryRow(ctx, shortNameExists, shortName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateLink = `-- name: UpdateLink :execrows
UPDATE links SET original_url = $2, short_name = $3, short_url = $4 WHERE id = $1 RETURNING id, original_url, short_name, short_url, created_at
`

type UpdateLinkParams struct {
	ID          int64
	OriginalUrl string
	ShortName   string
	ShortUrl    string
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLink,
		arg.ID,
		arg.OriginalUrl,
		arg.ShortName,
		arg.ShortUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
